### ISSUE TITLE
need .ipynb for fork of ffmpeg

### ISSUE THREAD

**Issue by Learner00100** [yunooooo/FFmpeg-for-Google-Drive#6]
thanks for FFmpeg-for-Google-Drive.
can i get .ipynb for this fork of ffmpeg https://github.com/makrsmark/FFmpeg.git
is it possible, please reply.

**Comment by yunooooo** [comment]
I've updated my notebook to use FFmpeg v5.0

If you want to use that specific fork, you'll need to set that up yourself. Sorry 😥

**Comment by Learner00100** [comment]
> I've updated my notebook to use FFmpeg v5.0
> 
> If you want to use that specific fork, you'll need to set that up yourself. Sorry disappointed_relieved

Thanks for updating to v5.
Can you tell how to create notebook from that fork ,so that I can do it, can you help me.

**Comment by yunooooo** [comment]
> > I've updated my notebook to use FFmpeg v5.0
> > If you want to use that specific fork, you'll need to set that up yourself. Sorry disappointed_relieved
> 
> Thanks for updating to v5. Can you tell how to create notebook from that fork ,so that I can do it, can you help me.

When you have the notebook open, go to **File** > **Save a copy in GitHub**

<img src="https://yuno.pw/i/Mvyr.png">

After you save it a fork will be created
